### ISSUE TITLE
Syntax error if extension is installed via TER - just hint, that php7.2 is needed

### ISSUE THREAD

**Issue by kaystrobach** [josefglatz/beuser_fastswitch#18]
Directly after installing the whole installation is broken.

As you use a type annotation, i would suggest, that you add the php 7.2 version requirement to the description of the extension.

Thank you!

<img width="453" alt="grafik" src="https://user-images.githubusercontent.com/1185776/63830882-8e728980-c96d-11e9-964d-4f5f23150f8f.png">

**Comment by josefglatz** [comment]
OH, thx

**Comment by josefglatz** [comment]
should I make it working with php < 7.2?

**Comment by kaystrobach** [comment]
nope 7.2 is ok - just the hint would be awesome.
