### ISSUE TITLE
Support for big TYPO3 instance: Ajax autocomplete search box

### ISSUE THREAD

**Issue by josefglatz** [josefglatz/beuser_fastswitch#5]

**Comment by AMartinNo1** [comment]
Is this feature in development already? I am having a T3 8 LTS instance with lots of users and would need a feature like that.

**Comment by AMartinNo1** [comment]
@josefglatz Thus you are busy I hope you find time to review this PR and merge if you accept the change. I have tested it with TYPO3 9.5.5.

**Comment by josefglatz** [comment]
Thx @AMartinNo1. I try to release the new version today for 9.5LTS!
