### ISSUE TITLE
Icons in popup not recognizable in light mode

### ISSUE THREAD

**Issue by wowaTYPO3** [josefglatz/beuser_fastswitch#50]
I always use the light mode on MacOs, so the icons to switch the user or show the information are not really visible.

![2023-09-07_19-46-48](https://github.com/josefglatz/beuser_fastswitch/assets/343511/7fdeedc4-7e6f-4081-a41f-22f8e9e971b7)

**Comment by josefglatz** [comment]
Thank you WoWa! I will come up with a fix to support dark and light mode :-)

**Comment by josefglatz** [comment]
Fix is also needed in dark mode:

<img width="371" alt="image" src="https://github.com/josefglatz/beuser_fastswitch/assets/2861556/d2ffe2e5-88b0-42b2-b436-e1a2f29bfdce">

**Comment by josefglatz** [comment]
Fixed in dev-main. Will be available in TER with next upcoming TER release. For now, just use composer or git to install dev-main or the latest tagged versions.
